In [59]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Samuel\Documents\Crime_Reports_20240701.csv")
df

,File Number,Date of Report,Crime Date Time,Crime,Reporting Area,Neighborhood,Location
0,2009-01323,02/21/2009 09:53:00 AM,02/21/2009 09:20 - 09:30,Threats,105.0,East Cambridge,"100 OTIS ST, Cambridge, MA"
1,2009-01324,02/21/2009 09:59:00 AM,02/20/2009 22:30 - 02/21/2009 10:00,Auto Theft,1109.0,North Cambridge,"400 RINDGE AVE, Cambridge, MA"
2,2009-01327,02/21/2009 12:32:00 PM,02/19/2009 21:00 - 02/21/2009 12:00,Hit and Run,1109.0,North Cambridge,"400 RINDGE AVE, Cambridge, MA"
3,2009-01331,02/21/2009 03:05:00 PM,02/21/2009 15:00 - 15:10,Larceny (Misc),1303.0,Strawberry Hill,"0 NORUMBEGA ST, Cambridge, MA"
4,2009-01346,02/22/2009 05:02:00 AM,02/22/2009 05:02,OUI,105.0,East Cambridge,"FIFTH ST & GORE ST, Cambridge, MA"
...,...,...,...,...,...,...,...
95918,2024-03755,05/07/2024 01:13:00 PM,05/04/2024 12:00 - 18:00,Larceny from MV,411.0,Area 4,"100 BISHOP ALLEN DR, Cambridge, MA"
95919,2024-03756,05/07/2024 02:41:00 PM,05/07/2024 14:40 - 14:41,Accident,611.0,Mid-Cambridge,"MASSACHUSETTS AVE & PEABODY ST, Cambridge, MA"
95920,2024-03777,05/07/2024 08:13:00 PM,05/07/2024 15:00 - 19:15,Larceny of Bicycle,411.0,Area 4,"0 COLUMBIA ST, Cambridge, MA"
95921,2024-03806,05/08/2024 04:09:00 PM,05/07/2024 04:00 - 04:05,Larceny from MV,1005.0,West Cambridge,"0 FOSTER PL, Cambridge, MA"
95922,2024-03824,05/09/2024 10:23:00 AM,05/05/2024 11:30 - 13:00,Hit and Run,1204.0,Highlands,"200 Alewife Brook Pky, Cambridge, MA"

In [60]:
df["Crime"].value_counts()

Crime
Hit and Run               9150
Larceny from MV           7398
Larceny of Bicycle        6310
Mal. Dest. Property       6156
Forgery                   6142
Shoplifting               5611
Larceny from Building     4467
Warrant Arrest            4410
Simple Assault            4205
Larceny from Residence    3982
Housebreak                3846
Larceny from Person       3232
Admin Error               2874
Accident                  2873
Threats                   2775
Flim Flam                 2589
Aggravated Assault        2402
Missing Person            1969
Auto Theft                1947
Harassment                1534
Street Robbery            1223
Suspicious Package        1126
Drugs                     1086
Commercial Break          1016
Trespassing                747
Larceny (Misc)             703
OUI                        590
Phone Calls                529
Disorderly                 494
Larceny of Plate           437
Taxi Violation             404
Indecent Exposure          390
Commercial Robbery         368
Drinking in Public         362
Rec. Stol. Property        326
Larceny of Services        304
Violation of H.O.          298
Counterfeiting             257
Weapon Violations          167
Noise Complaint            166
Extortion/Blackmail        164
Embezzlement               157
Arson                      148
Annoying & Accosting       148
Sex Offender Violation      94
Peeping & Spying            83
Liquor Possession/Sale      74
Prostitution                73
Stalking                    41
Kidnapping                  34
Homicide                    21
Domestic Dispute            10
Violation of R.O.            7
Gambling                     4
Name: count, dtype: int64

In [61]:
df=df.rename(columns={"Crime Date Time": "incident_date_time", "Crime": "incident_type", "Neighborhood": "neighborhood","Location": "location"})

In [62]:
df

,File Number,Date of Report,incident_date_time,incident_type,Reporting Area,neighborhood,location
0,2009-01323,02/21/2009 09:53:00 AM,02/21/2009 09:20 - 09:30,Threats,105.0,East Cambridge,"100 OTIS ST, Cambridge, MA"
1,2009-01324,02/21/2009 09:59:00 AM,02/20/2009 22:30 - 02/21/2009 10:00,Auto Theft,1109.0,North Cambridge,"400 RINDGE AVE, Cambridge, MA"
2,2009-01327,02/21/2009 12:32:00 PM,02/19/2009 21:00 - 02/21/2009 12:00,Hit and Run,1109.0,North Cambridge,"400 RINDGE AVE, Cambridge, MA"
3,2009-01331,02/21/2009 03:05:00 PM,02/21/2009 15:00 - 15:10,Larceny (Misc),1303.0,Strawberry Hill,"0 NORUMBEGA ST, Cambridge, MA"
4,2009-01346,02/22/2009 05:02:00 AM,02/22/2009 05:02,OUI,105.0,East Cambridge,"FIFTH ST & GORE ST, Cambridge, MA"
...,...,...,...,...,...,...,...
95918,2024-03755,05/07/2024 01:13:00 PM,05/04/2024 12:00 - 18:00,Larceny from MV,411.0,Area 4,"100 BISHOP ALLEN DR, Cambridge, MA"
95919,2024-03756,05/07/2024 02:41:00 PM,05/07/2024 14:40 - 14:41,Accident,611.0,Mid-Cambridge,"MASSACHUSETTS AVE & PEABODY ST, Cambridge, MA"
95920,2024-03777,05/07/2024 08:13:00 PM,05/07/2024 15:00 - 19:15,Larceny of Bicycle,411.0,Area 4,"0 COLUMBIA ST, Cambridge, MA"
95921,2024-03806,05/08/2024 04:09:00 PM,05/07/2024 04:00 - 04:05,Larceny from MV,1005.0,West Cambridge,"0 FOSTER PL, Cambridge, MA"
95922,2024-03824,05/09/2024 10:23:00 AM,05/05/2024 11:30 - 13:00,Hit and Run,1204.0,Highlands,"200 Alewife Brook Pky, Cambridge, MA"

In [63]:
incident_df = df[["incident_date_time", "incident_type", "neighborhood", "location"]]
incident_df

,incident_date_time,incident_type,neighborhood,location
0,02/21/2009 09:20 - 09:30,Threats,East Cambridge,"100 OTIS ST, Cambridge, MA"
1,02/20/2009 22:30 - 02/21/2009 10:00,Auto Theft,North Cambridge,"400 RINDGE AVE, Cambridge, MA"
2,02/19/2009 21:00 - 02/21/2009 12:00,Hit and Run,North Cambridge,"400 RINDGE AVE, Cambridge, MA"
3,02/21/2009 15:00 - 15:10,Larceny (Misc),Strawberry Hill,"0 NORUMBEGA ST, Cambridge, MA"
4,02/22/2009 05:02,OUI,East Cambridge,"FIFTH ST & GORE ST, Cambridge, MA"
...,...,...,...,...
95918,05/04/2024 12:00 - 18:00,Larceny from MV,Area 4,"100 BISHOP ALLEN DR, Cambridge, MA"
95919,05/07/2024 14:40 - 14:41,Accident,Mid-Cambridge,"MASSACHUSETTS AVE & PEABODY ST, Cambridge, MA"
95920,05/07/2024 15:00 - 19:15,Larceny of Bicycle,Area 4,"0 COLUMBIA ST, Cambridge, MA"
95921,05/07/2024 04:00 - 04:05,Larceny from MV,West Cambridge,"0 FOSTER PL, Cambridge, MA"
95922,05/05/2024 11:30 - 13:00,Hit and Run,Highlands,"200 Alewife Brook Pky, Cambridge, MA"

In [64]:
crime_mapping = {"Auto Theft": "Theft", "Larceny from MV": "Theft", "Larceny from Building": "Theft", "Larceny from Residence": "Theft", 
                 "Larceny from Person": "Theft", "Larceny (Misc)": "Theft","Larceny of Bicycle": "Theft","Larceny of Plate": "Theft",
                 "Larceny of Services": "Theft", "Shoplifting": "Theft", "Rec. Stol. Property": "Theft","Flim Flam": "Theft",
                 "Housebreak": "Burglary", "Commercial Break": "Burglary", "Street Robbery": "Robbery","Commercial Robbery": "Robbery",
                 "Aggravated Assault": "Assault", "Simple Assault": "Assault", "Threats": "Security Threat", "Suspicious Package": "Security Threat",
                 "Weapon Violations": "Security Threat", "Trespassing": "Unauthorized Access", "Peeping & Spying": "Unauthorized Access",
                 "Arson": "Fire", "Accident": "Accident","Hit and Run": "Accident", "Missing Person": "Missing Person", "Drugs": "Drugs",
                 "Liquor Possession/Sale": "Drugs", "Drinking in Public": "Drugs", "Forgery": "Fraud", "Counterfeiting": "Fraud",
                 "Embezzlement": "Fraud", "Extortion/Blackmail": "Fraud"}
incident_df["incident_type"] = incident_df["incident_type"].replace(crime_mapping)

C:\Users\Samuel\AppData\Local\Temp\ipykernel_1044\1159831573.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  incident_df["incident_type"] = incident_df["incident_type"].replace(crime_mapping)

In [65]:
incident_df

,incident_date_time,incident_type,neighborhood,location
0,02/21/2009 09:20 - 09:30,Security Threat,East Cambridge,"100 OTIS ST, Cambridge, MA"
1,02/20/2009 22:30 - 02/21/2009 10:00,Theft,North Cambridge,"400 RINDGE AVE, Cambridge, MA"
2,02/19/2009 21:00 - 02/21/2009 12:00,Accident,North Cambridge,"400 RINDGE AVE, Cambridge, MA"
3,02/21/2009 15:00 - 15:10,Theft,Strawberry Hill,"0 NORUMBEGA ST, Cambridge, MA"
4,02/22/2009 05:02,OUI,East Cambridge,"FIFTH ST & GORE ST, Cambridge, MA"
...,...,...,...,...
95918,05/04/2024 12:00 - 18:00,Theft,Area 4,"100 BISHOP ALLEN DR, Cambridge, MA"
95919,05/07/2024 14:40 - 14:41,Accident,Mid-Cambridge,"MASSACHUSETTS AVE & PEABODY ST, Cambridge, MA"
95920,05/07/2024 15:00 - 19:15,Theft,Area 4,"0 COLUMBIA ST, Cambridge, MA"
95921,05/07/2024 04:00 - 04:05,Theft,West Cambridge,"0 FOSTER PL, Cambridge, MA"
95922,05/05/2024 11:30 - 13:00,Accident,Highlands,"200 Alewife Brook Pky, Cambridge, MA"

In [66]:
incident_df["incident_type"].value_counts()

incident_type
Theft                     37306
Accident                  12023
Fraud                      6720
Assault                    6607
Mal. Dest. Property        6156
Burglary                   4862
Warrant Arrest             4410
Security Threat            4068
Admin Error                2874
Missing Person             1969
Robbery                    1591
Harassment                 1534
Drugs                      1522
Unauthorized Access         830
OUI                         590
Phone Calls                 529
Disorderly                  494
Taxi Violation              404
Indecent Exposure           390
Violation of H.O.           298
Noise Complaint             166
Annoying & Accosting        148
Fire                        148
Sex Offender Violation       94
Prostitution                 73
Stalking                     41
Kidnapping                   34
Homicide                     21
Domestic Dispute             10
Violation of R.O.             7
Gambling                      4
Name: count, dtype: int64

In [67]:
df.to_csv("incident_df.csv", index=False)

In [51]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Samuel\Documents\walmart_2018_11_06.csv")
df

,index,name,url,street_address,city,state,zip_code,country,phone_number_1,phone_number_2,...,email_2,website,open_hours,latitude,longitude,facebook,twitter,instagram,pinterest,youtube
0,0,Conway Supercenter,https://www.walmart.com/store/5/conway-ar/details,1155 Hwy 65 North,Conway,AR,72032,US,501-329-0023,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",35.108660,-92.436905,NaN,NaN,NaN,NaN,NaN
1,1,Sikeston Supercenter,https://www.walmart.com/store/9/sikeston-mo/de...,1303 S Main St,Sikeston,MO,63801,US,573-472-3020,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",36.857394,-89.586051,NaN,NaN,NaN,NaN,NaN
2,2,Tahlequah Supercenter,https://www.walmart.com/store/10/tahlequah-ok/...,2020 S Muskogee Ave,Tahlequah,OK,74464,US,918-456-8804,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",35.888765,-94.979859,NaN,NaN,NaN,NaN,NaN
3,3,Mountain Home Supercenter,https://www.walmart.com/store/11/mountain-home...,65 Wal Mart Dr,Mountain Home,AR,72653,US,870-492-9299,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",36.354957,-92.341026,NaN,NaN,NaN,NaN,NaN
4,4,Claremore Supercenter,https://www.walmart.com/store/12/claremore-ok/...,1500 S Lynn Riggs Blvd,Claremore,OK,74017,US,918-341-2765,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",36.293955,-95.627125,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4649,4649,Pearland Neighborhood Market,https://www.walmart.com/store/7361/pearland-tx...,12631 Broadway Street,Pearland,TX,77584,US,713-570-7925,NaN,...,NaN,NaN,"monday - friday : 06:00-23:00, saturday : 06:0...",29.556350,-95.415783,NaN,NaN,NaN,NaN,NaN
4650,4650,Bentonville Gas Station,https://www.walmart.com/store/7368/bentonville...,1300 S Walton Blvd,Bentonville,AR,72712,US,479-271-2209,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",36.357486,-94.214669,NaN,NaN,NaN,NaN,NaN
4651,4651,Millcreek Pickup only,https://www.walmart.com/store/8855/millcreek-u...,3701 S Highland Dr,Millcreek,UT,84106,US,801-467-2882,NaN,...,NaN,NaN,"monday - friday : 08:00-20:00, saturday : 08:0...",40.691031,-111.846529,NaN,NaN,NaN,NaN,NaN
4652,4652,Dallas Supercenter,https://www.walmart.com/store/8930/dallas-tx/d...,15757 Coit Rd,Dallas,TX,75248,US,972-235-0681,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",32.963412,-96.770294,NaN,NaN,NaN,NaN,NaN
4653,4653,Murray Pickup only,https://www.walmart.com/store/8862/murray-ut/d...,5596 S Van Winkle Expy,Murray,UT,84117,US,801-278-8290,NaN,...,NaN,NaN,"monday - friday : 08:00-20:00, saturday : 08:0...",40.649827,-111.849349,NaN,NaN,NaN,NaN,NaN

In [52]:
df.columns

Index(['index', 'name', 'url', 'street_address', 'city', 'state', 'zip_code',
       'country', 'phone_number_1', 'phone_number_2', 'fax_1', 'fax_2',
       'email_1', 'email_2', 'website', 'open_hours', 'latitude', 'longitude',
       'facebook', 'twitter', 'instagram', 'pinterest', 'youtube'],
      dtype='object')

In [53]:
df = df.rename(columns={"name": "site_name", "street_address": "street_address", "city": "city", "state": "state",
                                  "zip_code": "zip_code", "country": "country", "latitude": "latitude", "longitude": "longitude"})

In [54]:
df

,index,site_name,url,street_address,city,state,zip_code,country,phone_number_1,phone_number_2,...,email_2,website,open_hours,latitude,longitude,facebook,twitter,instagram,pinterest,youtube
0,0,Conway Supercenter,https://www.walmart.com/store/5/conway-ar/details,1155 Hwy 65 North,Conway,AR,72032,US,501-329-0023,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",35.108660,-92.436905,NaN,NaN,NaN,NaN,NaN
1,1,Sikeston Supercenter,https://www.walmart.com/store/9/sikeston-mo/de...,1303 S Main St,Sikeston,MO,63801,US,573-472-3020,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",36.857394,-89.586051,NaN,NaN,NaN,NaN,NaN
2,2,Tahlequah Supercenter,https://www.walmart.com/store/10/tahlequah-ok/...,2020 S Muskogee Ave,Tahlequah,OK,74464,US,918-456-8804,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",35.888765,-94.979859,NaN,NaN,NaN,NaN,NaN
3,3,Mountain Home Supercenter,https://www.walmart.com/store/11/mountain-home...,65 Wal Mart Dr,Mountain Home,AR,72653,US,870-492-9299,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",36.354957,-92.341026,NaN,NaN,NaN,NaN,NaN
4,4,Claremore Supercenter,https://www.walmart.com/store/12/claremore-ok/...,1500 S Lynn Riggs Blvd,Claremore,OK,74017,US,918-341-2765,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",36.293955,-95.627125,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4649,4649,Pearland Neighborhood Market,https://www.walmart.com/store/7361/pearland-tx...,12631 Broadway Street,Pearland,TX,77584,US,713-570-7925,NaN,...,NaN,NaN,"monday - friday : 06:00-23:00, saturday : 06:0...",29.556350,-95.415783,NaN,NaN,NaN,NaN,NaN
4650,4650,Bentonville Gas Station,https://www.walmart.com/store/7368/bentonville...,1300 S Walton Blvd,Bentonville,AR,72712,US,479-271-2209,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",36.357486,-94.214669,NaN,NaN,NaN,NaN,NaN
4651,4651,Millcreek Pickup only,https://www.walmart.com/store/8855/millcreek-u...,3701 S Highland Dr,Millcreek,UT,84106,US,801-467-2882,NaN,...,NaN,NaN,"monday - friday : 08:00-20:00, saturday : 08:0...",40.691031,-111.846529,NaN,NaN,NaN,NaN,NaN
4652,4652,Dallas Supercenter,https://www.walmart.com/store/8930/dallas-tx/d...,15757 Coit Rd,Dallas,TX,75248,US,972-235-0681,NaN,...,NaN,NaN,"monday - friday : 00:00-24:00, saturday : 00:0...",32.963412,-96.770294,NaN,NaN,NaN,NaN,NaN
4653,4653,Murray Pickup only,https://www.walmart.com/store/8862/murray-ut/d...,5596 S Van Winkle Expy,Murray,UT,84117,US,801-278-8290,NaN,...,NaN,NaN,"monday - friday : 08:00-20:00, saturday : 08:0...",40.649827,-111.849349,NaN,NaN,NaN,NaN,NaN

In [55]:
site_df = df[["site_name", "street_address", "city", "state", "zip_code", "country", "latitude", "longitude"]]
site_df

,site_name,street_address,city,state,zip_code,country,latitude,longitude
0,Conway Supercenter,1155 Hwy 65 North,Conway,AR,72032,US,35.108660,-92.436905
1,Sikeston Supercenter,1303 S Main St,Sikeston,MO,63801,US,36.857394,-89.586051
2,Tahlequah Supercenter,2020 S Muskogee Ave,Tahlequah,OK,74464,US,35.888765,-94.979859
3,Mountain Home Supercenter,65 Wal Mart Dr,Mountain Home,AR,72653,US,36.354957,-92.341026
4,Claremore Supercenter,1500 S Lynn Riggs Blvd,Claremore,OK,74017,US,36.293955,-95.627125
...,...,...,...,...,...,...,...,...
4649,Pearland Neighborhood Market,12631 Broadway Street,Pearland,TX,77584,US,29.556350,-95.415783
4650,Bentonville Gas Station,1300 S Walton Blvd,Bentonville,AR,72712,US,36.357486,-94.214669
4651,Millcreek Pickup only,3701 S Highland Dr,Millcreek,UT,84106,US,40.691031,-111.846529
4652,Dallas Supercenter,15757 Coit Rd,Dallas,TX,75248,US,32.963412,-96.770294
4653,Murray Pickup only,5596 S Van Winkle Expy,Murray,UT,84117,US,40.649827,-111.849349

In [56]:
site_df.isnull().sum()

site_name         0
street_address    0
city              0
state             0
zip_code          0
country           0
latitude          0
longitude         0
dtype: int64

In [70]:
df.to_csv("site_df.csv", index = False)

In [35]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Samuel\Downloads\employee_data.csv")
df

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
0,3427,Uriah,Bridges,20-Sep-19,NaN,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,...,Finance & Accounting,07-10-1969,MA,Accounting,Female,34904,White,Widowed,Fully Meets,4
1,3428,Paula,Small,11-Feb-23,NaN,Production Technician I,Renee Mccormick,paula.small@bilearner.com,EW,Active,...,Aerial,30-08-1965,MA,Labor,Male,6593,Hispanic,Widowed,Fully Meets,3
2,3429,Edward,Buck,10-Dec-18,NaN,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,...,General - Sga,06-10-1991,MA,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4
3,3430,Michael,Riordan,21-Jun-21,NaN,Area Sales Manager,Rebekah Wright,michael.riordan@bilearner.com,CCDR,Active,...,Finance & Accounting,04-04-1998,ND,Clerk,Male,58782,Other,Single,Fully Meets,2
4,3431,Jasmine,Onque,29-Jun-19,NaN,Area Sales Manager,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,...,General - Con,29-08-1969,FL,Laborer,Female,33174,Other,Married,Fully Meets,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,3422,Jakobe,Erickson,22-Jun-22,07-Aug-22,Production Technician I,Bethany Carter,jakobe.erickson@bilearner.com,PYZ,Leave of Absence,...,Engineers,23-06-1998,MA,Model Assistant,Female,44500,Other,Widowed,Fully Meets,3
2996,3423,Adyson,Strickland,28-Dec-20,NaN,Production Technician I,Caroline Harris,adyson.strickland@bilearner.com,SVG,Active,...,Engineers,10-06-2001,MA,Engineer,Male,35444,Black,Widowed,Fully Meets,3
2997,3424,Annabel,Wilkins,09-Dec-20,04-Aug-22,Production Technician I,Mr. James Castillo,annabel.wilkins@bilearner.com,TNS,Voluntarily Terminated,...,Wireline Construction,27-01-1997,MA,Laborer,Male,6608,White,Single,Fully Meets,2
2998,3425,Kendra,Braun,28-May-19,23-Oct-21,Production Technician I,Michael Woods,kendra.braun@bilearner.com,WBL,Voluntarily Terminated,...,Aerial,28-05-1954,MA,Foreman,Female,3807,Hispanic,Divorced,Fully Meets,2
2999,3426,Chace,Kerr,27-Apr-22,NaN,Production Technician I,Javier Mccall,chace.kerr@bilearner.com,BPC,Active,...,Field Operations,11-09-1990,MA,Warehouse Technician,Female,57487,White,Married,Fully Meets,2

In [37]:
df.columns

Index(['EmpID', 'FirstName', 'LastName', 'StartDate', 'ExitDate', 'Title',
       'Supervisor', 'ADEmail', 'BusinessUnit', 'EmployeeStatus',
       'EmployeeType', 'PayZone', 'EmployeeClassificationType',
       'TerminationType', 'TerminationDescription', 'DepartmentType',
       'Division', 'DOB', 'State', 'JobFunctionDescription', 'GenderCode',
       'LocationCode', 'RaceDesc', 'MaritalDesc', 'Performance Score',
       'Current Employee Rating'],
      dtype='object')

In [38]:
df["Title"].value_counts()

Title
Production Technician I         1321
Production Technician II         516
Area Sales Manager               297
Production Manager               154
Software Engineer                 90
IT Support                        88
Network Engineer                  55
Sr. Network Engineer              50
Data Analyst                      47
BI Developer                      44
Administrative Assistant          33
Accountant I                      33
Sales Manager                     30
Senior BI Developer               30
Database Administrator            25
IT Manager - DB                   22
Shared Services Manager           20
Sr. Accountant                    13
IT Manager - Support              11
Director of Sales                 11
Director of Operations            11
IT Manager - Infra                11
IT Director                       11
President & CEO                   11
BI Director                       11
CIO                               11
Software Engineering Manager      10
Data Analyst                       8
Sr. DBA                            8
Principal Data Architect           8
Data Architect                     5
Enterprise Architect               5
Name: count, dtype: int64

In [39]:
role_mapping = {"Production Technician I": "Security Guard", "Production Technician II": "Senior Security Guard", 
                "Area Sales Manager": "Site Supervisor", "Production Manager": "Operations Supervisor", 
                "Administrative Assistant": "Control Room Operator", "IT Support": "CCTV Operator",
                "Network Engineer": "Electronic Security Technician","Sr. Network Engineer": "Senior Electronic Security Technician",
                "IT Manager - Support": "Security Operations Manager", "Director of Operations": "Operations Manager",
                "President & CEO": "General Manager","CIO": "General Manager"}

In [42]:
df["Title"] = df["Title"].replace(role_mapping)
df

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
0,3427,Uriah,Bridges,20-Sep-19,NaN,Security Guard,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,...,Finance & Accounting,07-10-1969,MA,Accounting,Female,34904,White,Widowed,Fully Meets,4
1,3428,Paula,Small,11-Feb-23,NaN,Security Guard,Renee Mccormick,paula.small@bilearner.com,EW,Active,...,Aerial,30-08-1965,MA,Labor,Male,6593,Hispanic,Widowed,Fully Meets,3
2,3429,Edward,Buck,10-Dec-18,NaN,Site Supervisor,Crystal Walker,edward.buck@bilearner.com,PL,Active,...,General - Sga,06-10-1991,MA,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4
3,3430,Michael,Riordan,21-Jun-21,NaN,Site Supervisor,Rebekah Wright,michael.riordan@bilearner.com,CCDR,Active,...,Finance & Accounting,04-04-1998,ND,Clerk,Male,58782,Other,Single,Fully Meets,2
4,3431,Jasmine,Onque,29-Jun-19,NaN,Site Supervisor,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,...,General - Con,29-08-1969,FL,Laborer,Female,33174,Other,Married,Fully Meets,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,3422,Jakobe,Erickson,22-Jun-22,07-Aug-22,Security Guard,Bethany Carter,jakobe.erickson@bilearner.com,PYZ,Leave of Absence,...,Engineers,23-06-1998,MA,Model Assistant,Female,44500,Other,Widowed,Fully Meets,3
2996,3423,Adyson,Strickland,28-Dec-20,NaN,Security Guard,Caroline Harris,adyson.strickland@bilearner.com,SVG,Active,...,Engineers,10-06-2001,MA,Engineer,Male,35444,Black,Widowed,Fully Meets,3
2997,3424,Annabel,Wilkins,09-Dec-20,04-Aug-22,Security Guard,Mr. James Castillo,annabel.wilkins@bilearner.com,TNS,Voluntarily Terminated,...,Wireline Construction,27-01-1997,MA,Laborer,Male,6608,White,Single,Fully Meets,2
2998,3425,Kendra,Braun,28-May-19,23-Oct-21,Security Guard,Michael Woods,kendra.braun@bilearner.com,WBL,Voluntarily Terminated,...,Aerial,28-05-1954,MA,Foreman,Female,3807,Hispanic,Divorced,Fully Meets,2
2999,3426,Chace,Kerr,27-Apr-22,NaN,Security Guard,Javier Mccall,chace.kerr@bilearner.com,BPC,Active,...,Field Operations,11-09-1990,MA,Warehouse Technician,Female,57487,White,Married,Fully Meets,2

In [43]:
df["Title"].value_counts()

Title
Security Guard                           1321
Senior Security Guard                     516
Site Supervisor                           297
Operations Supervisor                     154
Software Engineer                          90
CCTV Operator                              88
Electronic Security Technician             55
Senior Electronic Security Technician      50
Data Analyst                               47
BI Developer                               44
Accountant I                               33
Control Room Operator                      33
Sales Manager                              30
Senior BI Developer                        30
Database Administrator                     25
IT Manager - DB                            22
General Manager                            22
Shared Services Manager                    20
Sr. Accountant                             13
BI Director                                11
Security Operations Manager                11
IT Manager - Infra                         11
Director of Sales                          11
Operations Manager                         11
IT Director                                11
Software Engineering Manager               10
Data Analyst                                8
Sr. DBA                                     8
Principal Data Architect                    8
Data Architect                              5
Enterprise Architect                        5
Name: count, dtype: int64

In [45]:
role_mapping = {"Software Engineer": "Security Systems Engineer", "Data Analyst": "Intelligence Analyst","BI Developer": "Intelligence Analyst",
                "Senior BI Developer": "Senior Intelligence Analyst","BI Director": "Intelligence Director",
                "Database Administrator": "Systems Administrator", "Sr. DBA": "Senior Systems Administrator", "IT Manager - DB": "Systems Manager",
                "IT Manager - Infra": "Infrastructure Manager","IT Director": "Technical Director","Software Engineering Manager": "Technical Manager",
                "Principal Data Architect": "Solutions Architect","Data Architect": "Solutions Architect",
                "Enterprise Architect": "Enterprise Solutions Architect","Accountant I": "Finance Officer","Sr. Accountant": "Senior Finance Officer",
                "Sales Manager": "Business Development Manager","Director of Sales": "Business Development Director",
                "Shared Services Manager": "Administration Manager"}
df["Title"] = df["Title"].replace(role_mapping)

In [46]:
df

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
0,3427,Uriah,Bridges,20-Sep-19,NaN,Security Guard,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,...,Finance & Accounting,07-10-1969,MA,Accounting,Female,34904,White,Widowed,Fully Meets,4
1,3428,Paula,Small,11-Feb-23,NaN,Security Guard,Renee Mccormick,paula.small@bilearner.com,EW,Active,...,Aerial,30-08-1965,MA,Labor,Male,6593,Hispanic,Widowed,Fully Meets,3
2,3429,Edward,Buck,10-Dec-18,NaN,Site Supervisor,Crystal Walker,edward.buck@bilearner.com,PL,Active,...,General - Sga,06-10-1991,MA,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4
3,3430,Michael,Riordan,21-Jun-21,NaN,Site Supervisor,Rebekah Wright,michael.riordan@bilearner.com,CCDR,Active,...,Finance & Accounting,04-04-1998,ND,Clerk,Male,58782,Other,Single,Fully Meets,2
4,3431,Jasmine,Onque,29-Jun-19,NaN,Site Supervisor,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,...,General - Con,29-08-1969,FL,Laborer,Female,33174,Other,Married,Fully Meets,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,3422,Jakobe,Erickson,22-Jun-22,07-Aug-22,Security Guard,Bethany Carter,jakobe.erickson@bilearner.com,PYZ,Leave of Absence,...,Engineers,23-06-1998,MA,Model Assistant,Female,44500,Other,Widowed,Fully Meets,3
2996,3423,Adyson,Strickland,28-Dec-20,NaN,Security Guard,Caroline Harris,adyson.strickland@bilearner.com,SVG,Active,...,Engineers,10-06-2001,MA,Engineer,Male,35444,Black,Widowed,Fully Meets,3
2997,3424,Annabel,Wilkins,09-Dec-20,04-Aug-22,Security Guard,Mr. James Castillo,annabel.wilkins@bilearner.com,TNS,Voluntarily Terminated,...,Wireline Construction,27-01-1997,MA,Laborer,Male,6608,White,Single,Fully Meets,2
2998,3425,Kendra,Braun,28-May-19,23-Oct-21,Security Guard,Michael Woods,kendra.braun@bilearner.com,WBL,Voluntarily Terminated,...,Aerial,28-05-1954,MA,Foreman,Female,3807,Hispanic,Divorced,Fully Meets,2
2999,3426,Chace,Kerr,27-Apr-22,NaN,Security Guard,Javier Mccall,chace.kerr@bilearner.com,BPC,Active,...,Field Operations,11-09-1990,MA,Warehouse Technician,Female,57487,White,Married,Fully Meets,2

In [47]:
df["Title"].value_counts()

Title
Security Guard                           1321
Senior Security Guard                     516
Site Supervisor                           297
Operations Supervisor                     154
Intelligence Analyst                       91
Security Systems Engineer                  90
CCTV Operator                              88
Electronic Security Technician             55
Senior Electronic Security Technician      50
Control Room Operator                      33
Finance Officer                            33
Business Development Manager               30
Senior Intelligence Analyst                30
Systems Administrator                      25
Systems Manager                            22
General Manager                            22
Administration Manager                     20
Senior Finance Officer                     13
Solutions Architect                        13
Intelligence Director                      11
Security Operations Manager                11
Infrastructure Manager                     11
Business Development Director              11
Operations Manager                         11
Technical Director                         11
Technical Manager                          10
Data Analyst                                8
Senior Systems Administrator                8
Enterprise Solutions Architect              5
Name: count, dtype: int64

In [48]:
df[df["Title"].str.contains("Data", case=False, na=False)]["Title"].value_counts()

Title
Data Analyst     8
Name: count, dtype: int64

In [49]:
df["Title"] = df["Title"].replace({
    "Data Analyst": "Intelligence Analyst"})

In [52]:
df["Title"].value_counts()

Title
Security Guard                           1321
Senior Security Guard                     516
Site Supervisor                           297
Operations Supervisor                     154
Intelligence Analyst                       91
Security Systems Engineer                  90
CCTV Operator                              88
Electronic Security Technician             55
Senior Electronic Security Technician      50
Control Room Operator                      33
Finance Officer                            33
Business Development Manager               30
Senior Intelligence Analyst                30
Systems Administrator                      25
Systems Manager                            22
General Manager                            22
Administration Manager                     20
Senior Finance Officer                     13
Solutions Architect                        13
Intelligence Director                      11
Security Operations Manager                11
Infrastructure Manager                     11
Business Development Director              11
Operations Manager                         11
Technical Director                         11
Technical Manager                          10
Data Analyst                                8
Senior Systems Administrator                8
Enterprise Solutions Architect              5
Name: count, dtype: int64

In [59]:
employee = df
df.to_csv("employee.csv", index=False)

In [10]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Samuel\Documents\employee.csv")
df.columns

Index(['EmpID', 'FirstName', 'LastName', 'StartDate', 'ExitDate', 'Title',
       'Supervisor', 'ADEmail', 'BusinessUnit', 'EmployeeStatus',
       'EmployeeType', 'PayZone', 'EmployeeClassificationType',
       'TerminationType', 'TerminationDescription', 'DepartmentType',
       'Division', 'DOB', 'State', 'JobFunctionDescription', 'GenderCode',
       'LocationCode', 'RaceDesc', 'MaritalDesc', 'Performance Score',
       'Current Employee Rating'],
      dtype='object')

In [11]:
df

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
0,3427,Uriah,Bridges,20-Sep-19,NaN,Security Guard,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,...,Finance & Accounting,07-10-1969,MA,Accounting,Female,34904,White,Widowed,Fully Meets,4
1,3428,Paula,Small,11-Feb-23,NaN,Security Guard,Renee Mccormick,paula.small@bilearner.com,EW,Active,...,Aerial,30-08-1965,MA,Labor,Male,6593,Hispanic,Widowed,Fully Meets,3
2,3429,Edward,Buck,10-Dec-18,NaN,Site Supervisor,Crystal Walker,edward.buck@bilearner.com,PL,Active,...,General - Sga,06-10-1991,MA,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4
3,3430,Michael,Riordan,21-Jun-21,NaN,Site Supervisor,Rebekah Wright,michael.riordan@bilearner.com,CCDR,Active,...,Finance & Accounting,04-04-1998,ND,Clerk,Male,58782,Other,Single,Fully Meets,2
4,3431,Jasmine,Onque,29-Jun-19,NaN,Site Supervisor,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,...,General - Con,29-08-1969,FL,Laborer,Female,33174,Other,Married,Fully Meets,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,3422,Jakobe,Erickson,22-Jun-22,07-Aug-22,Security Guard,Bethany Carter,jakobe.erickson@bilearner.com,PYZ,Leave of Absence,...,Engineers,23-06-1998,MA,Model Assistant,Female,44500,Other,Widowed,Fully Meets,3
2996,3423,Adyson,Strickland,28-Dec-20,NaN,Security Guard,Caroline Harris,adyson.strickland@bilearner.com,SVG,Active,...,Engineers,10-06-2001,MA,Engineer,Male,35444,Black,Widowed,Fully Meets,3
2997,3424,Annabel,Wilkins,09-Dec-20,04-Aug-22,Security Guard,Mr. James Castillo,annabel.wilkins@bilearner.com,TNS,Voluntarily Terminated,...,Wireline Construction,27-01-1997,MA,Laborer,Male,6608,White,Single,Fully Meets,2
2998,3425,Kendra,Braun,28-May-19,23-Oct-21,Security Guard,Michael Woods,kendra.braun@bilearner.com,WBL,Voluntarily Terminated,...,Aerial,28-05-1954,MA,Foreman,Female,3807,Hispanic,Divorced,Fully Meets,2
2999,3426,Chace,Kerr,27-Apr-22,NaN,Security Guard,Javier Mccall,chace.kerr@bilearner.com,BPC,Active,...,Field Operations,11-09-1990,MA,Warehouse Technician,Female,57487,White,Married,Fully Meets,2

In [15]:
df["employee_name"] = df["FirstName"] + " " + df["LastName"]
df[["employee_name", "FirstName", "LastName"]].head()

     employee_name FirstName LastName
0    Uriah Bridges     Uriah  Bridges
1      Paula Small     Paula    Small
2      Edward Buck    Edward     Buck
3  Michael Riordan   Michael  Riordan
4    Jasmine Onque   Jasmine    Onque

In [20]:
df = df.rename(columns= {"GenderCode": "gender", "StartDate": "hire_date", "EmployeeStatus": "employment_status","Title": "skill_level"})

In [21]:
df.columns

Index(['EmpID', 'FirstName', 'LastName', 'hire_date', 'ExitDate',
       'skill_level', 'Supervisor', 'ADEmail', 'BusinessUnit',
       'employment_status', 'EmployeeType', 'PayZone',
       'EmployeeClassificationType', 'TerminationType',
       'TerminationDescription', 'DepartmentType', 'Division', 'DOB', 'State',
       'JobFunctionDescription', 'gender', 'LocationCode', 'RaceDesc',
       'MaritalDesc', 'Performance Score', 'Current Employee Rating',
       'employee_name'],
      dtype='object')

In [22]:
Employee_df = df[["EmpID", "employee_name", "gender", "hire_date", "employment_status", "skill_level"]]
Employee_df.head()

,EmpID,employee_name,gender,hire_date,employment_status,skill_level
0,3427,Uriah Bridges,Female,20-Sep-19,Active,Security Guard
1,3428,Paula Small,Male,11-Feb-23,Active,Security Guard
2,3429,Edward Buck,Male,10-Dec-18,Active,Site Supervisor
3,3430,Michael Riordan,Male,21-Jun-21,Active,Site Supervisor
4,3431,Jasmine Onque,Female,29-Jun-19,Active,Site Supervisor

In [29]:
Employee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmpID              3000 non-null   int64
 1   employee_name      3000 non-null   object
 2   gender             3000 non-null   object
 3   hire_date          3000 non-null   datetime64[ns]
 4   employment_status  3000 non-null   object
 5   skill_level        3000 non-null   object
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 140.8+ KB

In [27]:
Employee_df["hire_date"] = pd.to_datetime(Employee_df["hire_date"])

C:\Users\Samuel\AppData\Local\Temp\ipykernel_1044\2444724073.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  Employee_df["hire_date"] = pd.to_datetime(Employee_df["hire_date"])
C:\Users\Samuel\AppData\Local\Temp\ipykernel_1044\2444724073.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Employee_df["hire_date"] = pd.to_datetime(Employee_df["hire_date"])

In [38]:
Employee_df["skill_level"].unique()

array(['Security Guard', 'Site Supervisor', 'Senior Security Guard',
       'CCTV Operator', 'Electronic Security Technician',
       'Senior Electronic Security Technician', 'Solutions Architect',
       'Enterprise Solutions Architect', 'Senior Systems Administrator',
       'Systems Administrator', 'Intelligence Analyst', 'Data Analyst ',
       'General Manager', 'Intelligence Director',
       'Senior Finance Officer', 'Technical Manager',
       'Security Systems Engineer', 'Administration Manager',
       'Senior Intelligence Analyst', 'Operations Supervisor',
       'Control Room Operator', 'Finance Officer',
       'Business Development Manager', 'Security Operations Manager',
       'Infrastructure Manager', 'Systems Manager',
       'Business Development Director', 'Operations Manager',
       'Technical Director'], dtype=object)

In [40]:
Employee_df["skill_level"] = Employee_df["skill_level"].str.strip()

C:\Users\Samuel\AppData\Local\Temp\ipykernel_1044\2288886223.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Employee_df["skill_level"] = Employee_df["skill_level"].str.strip()

In [42]:
Employee_df["skill_level"].unique()

array(['Security Guard', 'Site Supervisor', 'Senior Security Guard',
       'CCTV Operator', 'Electronic Security Technician',
       'Senior Electronic Security Technician', 'Solutions Architect',
       'Enterprise Solutions Architect', 'Senior Systems Administrator',
       'Systems Administrator', 'Intelligence Analyst', 'Data Analyst',
       'General Manager', 'Intelligence Director',
       'Senior Finance Officer', 'Technical Manager',
       'Security Systems Engineer', 'Administration Manager',
       'Senior Intelligence Analyst', 'Operations Supervisor',
       'Control Room Operator', 'Finance Officer',
       'Business Development Manager', 'Security Operations Manager',
       'Infrastructure Manager', 'Systems Manager',
       'Business Development Director', 'Operations Manager',
       'Technical Director'], dtype=object)

In [45]:
Employee_df.to_csv("employee_df.csv", index=False)

In [72]:
import pandas as pd
import numpy as np
site_df = pd.read_csv(r"C:\Users\Samuel\site_df.csv")
site_df

,File Number,Date of Report,incident_date_time,incident_type,Reporting Area,neighborhood,location
0,2009-01323,02/21/2009 09:53:00 AM,02/21/2009 09:20 - 09:30,Threats,105.0,East Cambridge,"100 OTIS ST, Cambridge, MA"
1,2009-01324,02/21/2009 09:59:00 AM,02/20/2009 22:30 - 02/21/2009 10:00,Auto Theft,1109.0,North Cambridge,"400 RINDGE AVE, Cambridge, MA"
2,2009-01327,02/21/2009 12:32:00 PM,02/19/2009 21:00 - 02/21/2009 12:00,Hit and Run,1109.0,North Cambridge,"400 RINDGE AVE, Cambridge, MA"
3,2009-01331,02/21/2009 03:05:00 PM,02/21/2009 15:00 - 15:10,Larceny (Misc),1303.0,Strawberry Hill,"0 NORUMBEGA ST, Cambridge, MA"
4,2009-01346,02/22/2009 05:02:00 AM,02/22/2009 05:02,OUI,105.0,East Cambridge,"FIFTH ST & GORE ST, Cambridge, MA"
...,...,...,...,...,...,...,...
95918,2024-03755,05/07/2024 01:13:00 PM,05/04/2024 12:00 - 18:00,Larceny from MV,411.0,Area 4,"100 BISHOP ALLEN DR, Cambridge, MA"
95919,2024-03756,05/07/2024 02:41:00 PM,05/07/2024 14:40 - 14:41,Accident,611.0,Mid-Cambridge,"MASSACHUSETTS AVE & PEABODY ST, Cambridge, MA"
95920,2024-03777,05/07/2024 08:13:00 PM,05/07/2024 15:00 - 19:15,Larceny of Bicycle,411.0,Area 4,"0 COLUMBIA ST, Cambridge, MA"
95921,2024-03806,05/08/2024 04:09:00 PM,05/07/2024 04:00 - 04:05,Larceny from MV,1005.0,West Cambridge,"0 FOSTER PL, Cambridge, MA"
95922,2024-03824,05/09/2024 10:23:00 AM,05/05/2024 11:30 - 13:00,Hit and Run,1204.0,Highlands,"200 Alewife Brook Pky, Cambridge, MA"

In [73]:
unique_sites = site_df[['location', 'neighborhood']].drop_duplicates().dropna().reset_index(drop=True)

print(f"Total unique physical sites found: {len(unique_sites)}")
print(unique_sites.head())

Total unique physical sites found: 5896
                               location     neighborhood
0            100 OTIS ST, Cambridge, MA   East Cambridge
1         400 RINDGE AVE, Cambridge, MA  North Cambridge
2         0 NORUMBEGA ST, Cambridge, MA  Strawberry Hill
3     FIFTH ST & GORE ST, Cambridge, MA   East Cambridge
4  600 Massachusetts Ave, Cambridge, MA    Cambridgeport

In [74]:
np.random.seed(42)
unique_sites['site_id'] = range(1, len(unique_sites) + 1)
unique_sites['contract_id'] = np.random.randint(1001, 1031, size=len(unique_sites))
unique_sites['site_name'] = (unique_sites['location'] + " - " + unique_sites['neighborhood']).str.slice(0, 145)
unique_sites['location_clean'] = unique_sites['location'].str.slice(0, 95)
unique_sites['site_size'] = np.random.choice(['Small', 'Medium', 'Large'], size=len(unique_sites))
unique_sites['status'] = np.random.choice(['Active', 'Active', 'Active', 'Inactive'], size=len(unique_sites))
final_sites = unique_sites[['site_id', 'contract_id', 'site_name', 'location_clean', 'site_size', 'status']]
final_sites.columns = ['site_id', 'contract_id', 'site_name', 'location', 'site_size', 'status']
final_sites.head()

,site_id,contract_id,site_name,location,site_size,status
0,1,1007,"100 OTIS ST, Cambridge, MA - East Cambridge","100 OTIS ST, Cambridge, MA",Large,Active
1,2,1020,"400 RINDGE AVE, Cambridge, MA - North Cambridge","400 RINDGE AVE, Cambridge, MA",Medium,Active
2,3,1029,"0 NORUMBEGA ST, Cambridge, MA - Strawberry Hill","0 NORUMBEGA ST, Cambridge, MA",Medium,Inactive
3,4,1015,"FIFTH ST & GORE ST, Cambridge, MA - East Cambr...","FIFTH ST & GORE ST, Cambridge, MA",Medium,Inactive
4,5,1011,"600 Massachusetts Ave, Cambridge, MA - Cambrid...","600 Massachusetts Ave, Cambridge, MA",Large,Active

In [75]:
final_sites.to_csv('ssis_sites.csv', index=False)

In [91]:
import pandas as pd

df_incidents = pd.read_csv(r"C:\Users\Samuel\Documents\incident_df.csv")
df_sites = pd.read_csv(r"C:\Users\Samuel\Documents\ssis_sites.csv")
df_employees = pd.read_csv(r"C:\Users\Samuel\Documents\employee_df.csv")

print("Incidents columns:", df_incidents.columns.tolist())
print("Sites columns:", df_sites.columns.tolist())
print("Employees columns:", df_employees.columns.tolist())

Incidents columns: ['File Number', 'Date of Report', 'incident_date_time', 'incident_type', 'Reporting Area', 'neighborhood', 'location']
Sites columns: ['site_id', 'contract_id', 'site_name', 'location', 'site_size', 'status']
Employees columns: ['EmpID', 'employee_name', 'gender', 'hire_date', 'employment_status', 'skill_level']

In [94]:
df_incidents['location'] = df_incidents['location'].astype(str).str.strip().str.lower()
df_incidents['incident_type'] = df_incidents['incident_type'].astype(str).str.strip().str.lower()
df_incidents['incident_datetime'] = pd.to_datetime(df_incidents['incident_date_time'], format='mixed', errors='coerce')
print(df_incidents[['location', 'incident_type', 'incident_datetime']].head())

                            location   incident_type   incident_datetime
0         100 otis st, cambridge, ma         threats                 NaT
1      400 rindge ave, cambridge, ma      auto theft                 NaT
2      400 rindge ave, cambridge, ma     hit and run                 NaT
3      0 norumbega st, cambridge, ma  larceny (misc)                 NaT
4  fifth st & gore st, cambridge, ma             oui 2009-02-22 05:02:00

In [95]:
print(df_incidents['incident_date_time'].head(10))

0               02/21/2009 09:20 - 09:30
1    02/20/2009 22:30 - 02/21/2009 10:00
2    02/19/2009 21:00 - 02/21/2009 12:00
3               02/21/2009 15:00 - 15:10
4                       02/22/2009 05:02
5               02/22/2009 21:39 - 21:45
6    02/20/2009 20:00 - 02/23/2009 10:00
7               02/23/2009 11:00 - 11:20
8                       02/23/2009 20:16
9    02/22/2009 19:30 - 02/23/2009 20:30
Name: incident_date_time, dtype: object

In [96]:
df_incidents['start_time_str'] = df_incidents['incident_date_time'].astype(str).str.split('-').str[0].str.strip()
df_incidents['incident_datetime'] = pd.to_datetime(df_incidents['start_time_str'], format='mixed', errors='coerce')
if 'date of report' in df_incidents.columns:
    df_incidents['report_date'] = pd.to_datetime(df_incidents['date of report'], format='mixed', errors='coerce')
    df_incidents['incident_datetime'] = df_incidents['incident_datetime'].fillna(df_incidents['report_date'])
print(df_incidents[['incident_date_time', 'incident_datetime']].head(10))

                    incident_date_time   incident_datetime
0             02/21/2009 09:20 - 09:30 2009-02-21 09:20:00
1  02/20/2009 22:30 - 02/21/2009 10:00 2009-02-20 22:30:00
2  02/19/2009 21:00 - 02/21/2009 12:00 2009-02-19 21:00:00
3             02/21/2009 15:00 - 15:10 2009-02-21 15:00:00
4                     02/22/2009 05:02 2009-02-22 05:02:00
5             02/22/2009 21:39 - 21:45 2009-02-22 21:39:00
6  02/20/2009 20:00 - 02/23/2009 10:00 2009-02-20 20:00:00
7             02/23/2009 11:00 - 11:20 2009-02-23 11:00:00
8                     02/23/2009 20:16 2009-02-23 20:16:00
9  02/22/2009 19:30 - 02/23/2009 20:30 2009-02-22 19:30:00

In [98]:
import numpy as np

df_sites = pd.read_csv(r"C:\Users\Samuel\Documents\ssis_sites.csv")
df_employees = pd.read_csv(r"C:\Users\Samuel\Documents\employee_df.csv")

df_sites['location'] = df_sites['location'].astype(str).str.strip().str.lower()

df_incidents = pd.merge(df_incidents, df_sites[['site_id', 'location']], on='location', how='left')

df_incidents['site_id'] = df_incidents['site_id'].fillna(1).astype(int)

emp_ids = df_employees['EmpID'].dropna().unique()
df_incidents['employee_id'] = np.random.choice(emp_ids, size=len(df_incidents))

print(df_incidents[['site_id', 'employee_id', 'location']].head(10))

   site_id  employee_id                           location
0        1         3573         100 otis st, cambridge, ma
1     4200         2138         100 otis st, cambridge, ma
2        2         1101      400 rindge ave, cambridge, ma
3      134         1866      400 rindge ave, cambridge, ma
4     4567         3161      400 rindge ave, cambridge, ma
5        2         1944      400 rindge ave, cambridge, ma
6      134         1706      400 rindge ave, cambridge, ma
7     4567         1112      400 rindge ave, cambridge, ma
8        3         1553      0 norumbega st, cambridge, ma
9        4         3547  fifth st & gore st, cambridge, ma

In [99]:
import numpy as np

severities = ['low', 'medium', 'high']
df_incidents['severity'] = np.random.choice(severities, size=len(df_incidents), p=[0.5, 0.35, 0.15])
df_incidents['response_time_minutes'] = np.random.randint(5, 46, size=len(df_incidents))
statuses = ['closed', 'under investigation', 'open']
df_incidents['status'] = np.random.choice(statuses, size=len(df_incidents), p=[0.8, 0.15, 0.05])
final_cols = ['site_id', 'employee_id', 'incident_datetime', 'incident_type', 'severity', 'response_time_minutes', 'status']
df_final = df_incidents[final_cols]
df_final.to_csv('cleaned_incidents.csv', index=False)
print(df_final.head())

   site_id  employee_id   incident_datetime incident_type severity  \
0        1         3573 2009-02-21 09:20:00       threats     high
1     4200         2138 2009-02-21 09:20:00       threats      low
2        2         1101 2009-02-20 22:30:00    auto theft     high
3      134         1866 2009-02-20 22:30:00    auto theft   medium
4     4567         3161 2009-02-20 22:30:00    auto theft   medium

   response_time_minutes               status
0                     31  under investigation
1                     15               closed
2                     15  under investigation
3                     20               closed
4                     35               closed

In [101]:
import pandas as pd
df_sites = pd.read_csv(r"C:\Users\Samuel\Documents\ssis_sites.csv")
print("Sites columns:", df_sites.columns.tolist())

Sites columns: ['site_id', 'contract_id', 'site_name', 'location', 'site_size', 'status']

In [102]:
df_clients = df_sites[['site_name', 'location']].drop_duplicates().reset_index(drop=True)
df_clients.columns = ['client_name', 'location']
df_clients['client_name'] = df_clients['client_name'].astype(str).str.strip().str.lower()
df_clients['location'] = df_clients['location'].astype(str).str.strip().str.lower()
print(df_clients.head())

                                         client_name  \
0        100 otis st, cambridge, ma - east cambridge
1    400 rindge ave, cambridge, ma - north cambridge
2    0 norumbega st, cambridge, ma - strawberry hill
3  fifth st & gore st, cambridge, ma - east cambr...
4  600 massachusetts ave, cambridge, ma - cambrid...

                               location
0            100 otis st, cambridge, ma
1         400 rindge ave, cambridge, ma
2         0 norumbega st, cambridge, ma
3     fifth st & gore st, cambridge, ma
4  600 massachusetts ave, cambridge, ma

In [103]:
df_clients.to_csv('cleaned_clients.csv', index=False)

In [105]:
import pandas as pd
import numpy as np

df_emp = pd.read_csv(r"C:\Users\Samuel\Documents\employee_df.csv")
emp_ids = df_emp['EmpID'].dropna().unique()
num_records = len(emp_ids)

df_assignments = pd.DataFrame({
    'assignment_id': range(1, num_records + 1),
    'emp_id': emp_ids,
    'site_id': np.random.randint(1, 101, size=num_records),
    'shift_status': np.random.choice(['Scheduled', 'Completed', 'Cancelled'], size=num_records, p=[0.1, 0.85, 0.05])})
df_assignments.to_csv('cleaned_assignments.csv', index=False)
df_attendance = pd.DataFrame({
    'assignment_id': df_assignments['assignment_id'],
    'attendance_status': np.random.choice(
        ['Present', 'Absent', 'Late', 'Excused'], 
        size=num_records, 
        p=[0.82, 0.08, 0.07, 0.03] )})
df_attendance.to_csv('cleaned_attendance.csv', index=False)
print("Done! 'cleaned_attendance.csv' has been successfully created.")
print(df_attendance.head())

Done! 'cleaned_attendance.csv' has been successfully created.
   assignment_id attendance_status
0              1           Present
1              2           Present
2              3           Excused
3              4           Present
4              5           Present

In [106]:
import pandas as pd
import numpy as np

df_emp = pd.read_csv(r"C:\Users\Samuel\Documents\employee_df.csv")
emp_ids = df_emp['EmpID'].dropna().unique()
num_records = len(emp_ids)

df_assignment = pd.DataFrame({
    'assignment_id': range(1, num_records + 1),
    'site_id': np.random.randint(1, 101, size=num_records),
    'employee_id': emp_ids,
    'shift_type': np.random.choice(['Morning', 'Evening', 'Night', 'Rotating'], size=num_records, p=[0.4, 0.3, 0.2, 0.1]),
    'assignment_date': pd.date_range(start='2026-01-01', periods=num_records, freq='h').strftime('%Y-%m-%d')})
df_assignment.to_csv('cleaned_assignments.csv', index=False)
print("Successfully regenerated 'cleaned_assignments.csv' with the correct columns!")
print(df_assignment.head())

Successfully regenerated 'cleaned_assignments.csv' with the correct columns!
   assignment_id  site_id  employee_id shift_type assignment_date
0              1       85         3427   Rotating      2026-01-01
1              2       10         3428      Night      2026-01-01
2              3       51         3429      Night      2026-01-01
3              4       54         3430    Morning      2026-01-01
4              5       65         3431   Rotating      2026-01-01

In [108]:
import pandas as pd
import numpy as np

df_emp = pd.read_csv('employee.csv')
num_records = len(df_emp)

df_contracts = pd.DataFrame({
    'contract_id': range(1, num_records + 1),
    'client_id': np.random.randint(1, 50, size=num_records),
    'contract_type': np.random.choice(['Service Agreement', 'Security Provision', 'Consulting', 'Fixed-Term'], size=num_records, p=[0.4, 0.3, 0.2, 0.1]),
    'contract_start': df_emp['hire_date'],
    'contract_end': pd.date_range(start='2028-01-01', periods=num_records, freq='D').strftime('%Y-%m-%d'),
    'contract_value': np.random.uniform(5000.0, 150000.0, size=num_records).round(2),
    'status': np.random.choice(['Active', 'Pending', 'Terminated', 'Completed'], size=num_records, p=[0.75, 0.1, 0.05, 0.1])
})

df_contracts.to_csv('cleaned_contracts.csv', index=False)
print("Done! 'cleaned_contracts.csv' has been created.")

Done! 'cleaned_contracts.csv' has been created.